### PR TITLE
Introducing 'model' config for allowing developer to extend Site model

### PR DESCRIPTION
**Pull request by zssarkany**

### CODE REVIEW

**Comment by zssarkany** [comment]
Hm.. I think StyleCI check would fail without my changes as well. At least I hope :)
Sadly I don't use StyleCI, therefore I don't know what to do with this issue.

**Comment by gizburdt** [comment]
Thanks for your PR! :)

I don't think the env('MULTISITE_MODEL') is needed. Just set the name of the model in de config file, without the env function. Is there a specific reason you used the env function?

**Comment by zssarkany** [comment]
There is no specific reason for it, I don't plan to utilize it, furthermore any developer is able to change it to be env-aware if needed. I thought, that this approach is a bit fancier, but obviously it is an unnecessary env() invocation.

What should I do? Close this PR and create another?
(This is my first PR and I don't know what tools are provided by Github for you to fix this.)

In case of you accept my solution, it would be also great to have these changes in a v1.0.1 via composer. I don't know that do you need to do for it, but can you please do it as well? :)

**Comment by gizburdt** [comment]
Hi, sorry, missed your reply. If you push a new commit to your branch, it will be added to this PR automatically.

**Comment by zssarkany** [comment]
Hi @gizburdt,
no problem.
I've pushed the change we discussed earlier.

**Comment by gizburdt** [comment]
@zssarkany Thanks for your PR. I tagged version 1.1.0

**Comment by zssarkany** [comment]
Thanks @gizburdt ! :)
I can eliminate now my ugly solution for autoloading my version.

**Pull request merged**
